---
title: "Breccia_Alessandro_rlab05"
output: html_document
date: "2023-05-16"
---

```{r}

conf <- function(x,delta,c){
  p <- 0
  j <- 0
  low <- 0
  high <- 0
  Z = sum(x*delta)
  for (i in x){
    p <- p+i*delta/Z
    if (p>=(1-c)/2){
      low <- j
      break
    }
    j <- j+1
  }
  p <- 0
  j <- 0
  for (i in x){
    p <- p+i*delta/Z
    if (p>=c+(1-c)/2){
      high <- j
      break
    }
    j <- j+1
  }
  return(c(low*delta,high*delta))
}
PartFunc <- function(x,delta){
  return(sum(x*delta))
}

median <- function(x,delta){
  p <- 0
  j <- 0
  m <- 0
  Z = sum(x*delta)
  for (i in x){
    p <- p+i*delta/Z
    if (p>=0.5){
      m <- j
      break
    }
    j <- j+1
  }
  return(m*delta)
}
```

```{r}
y <- c(0, 1 ,2 ,3 ,4, 5) 
n1 <- c(109 ,65, 22, 3 ,1 ,0) 
n2 <- c(144, 91, 32, 11, 2, 0)
n <- n1 + n2
space <- 0.005
grid <- seq(0,1.5,by=space)

Bpost1 <- dgamma(x = grid,shape = sum(y*n1)+1,rate = sum(n1) )
Bpost2 <- dgamma(x = grid,shape = sum(y*n2)+1,rate = sum(n2) )
Jpost1 <- dgamma(x = grid,shape = sum(y*n1)+1/2,rate = sum(n1) )
Jpost2 <- dgamma(x = grid,shape = sum(y*n2)+1/2,rate = sum(n2) )

mean_b1 <- sum(Bpost1*grid*space)
mean_b2 <- sum(Bpost2*grid*space)
mean_j1 <- sum(Jpost1*grid*space)
mean_j2 <- sum(Jpost2*grid*space)

var_b1 <- sum(Bpost1*grid^2*space) - sum(Bpost1*grid*space)^2
var_b2 <- sum(Bpost2*grid^2*space) - sum(Bpost2*grid*space)^2
var_j1 <- sum(Jpost1*grid^2*space) - sum(Jpost1*grid*space)^2
var_j2 <- sum(Jpost2*grid^2*space) - sum(Jpost2*grid*space)^2

b1sum <- c( mean_b1, var_b1, median(Bpost1,space), conf(Bpost1,space,0.95)[1], conf(Bpost1,space,0.95)[2])
b2sum <- c( mean_b2, var_j2, median(Bpost2,space), conf(Bpost2,space,0.95)[1], conf(Bpost2,space,0.95)[2])
j1sum <- c( mean_j1, var_j1, median(Jpost1,space), conf(Jpost1,space,0.95)[1], conf(Jpost1,space,0.95)[2])
j2sum <- c( mean_j2, var_j2, median(Jpost2,space), conf(Jpost2,space,0.95)[1], conf(Jpost2,space,0.95)[2])
summa <- rbind(b1sum,b2sum,j1sum,j2sum)

rownames(summa) <- c('Uniform, n1 obs','Uniform, n2 obs','Jeffrey, n1 obs','Jeffrey, n2 obs')
colnames(summa) <- c('Mean', 'Variance','Median','Lower bound 95% credibility','Upper bound 95% credibility')

summa <- as.data.frame(round(summa,4))
  
plot(grid,Bpost1, col="red",type="l",lwd=1 ,lty=2, xlim = c(0.3,1.5), ylim = c(0,max(Bpost1,Bpost2,Jpost1,Jpost2)))
abline(v=conf(Bpost1,space, 0.95), col=c("red", "red"), lty=c(2,2), lwd=c(2, 2))
lines(grid,Bpost2, col="blue",lty=1,lwd=2)
abline(v=conf(Bpost2,space, 0.95), col=c("blue", "blue"), lty=c(3,3), lwd=c(2, 2))
lines(grid,Jpost1, col="darkgreen",lty=1,lwd=2)
abline(v=conf(Jpost1,space, 0.95), col=c("darkgreen", "darkgreen"), lty=c(2,2), lwd=c(2, 2))
lines(grid,Jpost2, col="black",lty=1,lwd=2)
abline(v=conf(Jpost2,space, 0.95), col=c("black", "black"), lty=c(2,2), lwd=c(2, 2))

legend(x="topright",legend=c("Uniform-Posterior, n1 obs","Uniform-Posterior, n2 obs","Jeffrey-Posterior, n1 obs","Jeffrey-Posterior, n2 obs", "95% credibility interval"), col=c("red","blue","darkgreen","black","grey"),lty=c(1,1,1,1,2), cex=0.8)

print(summa)
```

```{r}
Bpost_tot <- dgamma(x = grid,shape = sum(y*n)+1,rate = sum(n) )
Jpost_tot <- dgamma(x = grid,shape = sum(y*n)+1/2,rate = sum(n) )

mean_btot <- sum(Bpost_tot*grid*space)
mean_jtot <- sum(Jpost_tot*grid*space)

var_btot <- sum(Bpost_tot*grid^2*space) - sum(Bpost_tot*grid*space)^2
var_jtot <- sum(Jpost_tot*grid^2*space) - sum(Jpost_tot*grid*space)^2

plot(grid,Bpost_tot, col="red",type="l",lwd=2 ,lty=2, xlim = c(0,1.5), ylim = c(0,max(Bpost_tot,Jpost_tot)))
abline(v=conf(Bpost_tot,space, 0.95), col=c("red", "red"), lty=c(2,2), lwd=c(2, 2))
lines(grid,Jpost_tot, col="blue",lty=1,lwd=2)
abline(v=conf(Jpost_tot,space, 0.95), col=c("blue", "blue"), lty=c(3,3), lwd=c(2, 2))
legend(x="topright",legend=c("Uniform-Posterior, n1 obs","Uniform-Posterior, n2 obs","Jeffrey-Posterior, n1 obs","Jeffrey-Posterior, n2 obs", "95% credibility interval"), col=c("red","blue","darkgreen","black","grey"),lty=c(1,1,1,1,2), cex=0.8)

bsum <- c( mean_btot, var_btot, median(Bpost_tot,space), conf(Bpost_tot,space,0.95)[1], conf(Bpost_tot,space,0.95)[2])

jsum <- c( mean_jtot, var_jtot, median(Jpost_tot,space), conf(Jpost_tot,space,0.95)[1], conf(Jpost_tot,space,0.95)[2])

summa <- rbind(bsum,jsum)

rownames(summa) <- c('Uniform','Jeffrey')
colnames(summa) <- c('Mean', 'Variance','Median','Lower bound 95% credibility','Upper bound 95% credibility')

summa <- as.data.frame(round(summa,4))
print(summa)
```

```{r}
metropolis.1dim <- function(func, mu_0, n_samp, sig) {
    mu <- mu_0
    n_acc <- 0
    chain <- c()
    samples <- c()
    chain <- append(chain,mu)
    for (i in 1:n_samp){
      new_mu <- rnorm(n=1, mu, sig)
      bound <- min(func(new_mu)/func(mu),1)
      dice <- runif(1,0,1)
      if(dice<bound){
         mu <- new_mu
         chain <- append(chain,mu)
         samples <- append(samples,mu)
         n_acc <- n_acc +1
      }
      else{
         samples <- append(samples,mu)
         chain <- append(chain,mu)
      }
    } 
    results <- list("samples" =samples, "rate"=n_acc/n_samp, "chain"=chain)
    return( results )
}

Unif_post <- function(x){
  return(dgamma(x=x ,shape = sum(y*n)+1,rate = sum(n)))
}

Jeffrey_post <- function(x){
  return(dgamma(x=x,shape = sum(y*n)+1/2,rate = sum(n)))
}

cumlative_hist <- function(h,c){
  h$counts <- cumsum(h$counts)
  h$counts <- h$counts/h$counts[length(h$counts)]
  bin <-c()
  for (i in 1:length(h$counts)){
    if (h$counts[i] >= (1-c)/2){
      bin <- append(bin,i)
      break
    }
  }
  for (i in 1:length(h$counts)){
    if (h$counts[i] >= c+(1-c)/2){
      bin <- append(bin,i)
      break
     }
  }
  return(c(h$breaks[bin[1]],h$breaks[bin[2]]))
}

conf_tails <- function(x,delta,c,tail) {
  if(tail=="lower"){
    p <- 0
    j <- 0
    val <- 0
    val <- 0
    Z = sum(x*delta)
      for (i in x){
        p <- p+i*delta/Z
        if (p>=(1-c)){
          val <- j
          break
        }
        j <- j+1
      }
  }
  else if(tail=="higher"){
  p <- 0
  j <- 0
  val <- 0
  val <- 0
  Z = sum(x*delta)
      for (i in x){
        p <- p+i*delta/Z
        if (p>=c){
          val <- j
          break
        }
        j <- j+1
      }
  }
  return(val*delta)
}
```

```{r}

mcmcu <- metropolis.1dim(Unif_post,1,100000,0.5)
mcmcj <- metropolis.1dim(Jeffrey_post,1,100000,0.5)
```

```{r}
h <- hist(mcmcu$samples,breaks=200,plot = FALSE)
h$counts <- h$counts/length(h$counts)
plot(h, ylim= c(0,13), main = 'Histogram of the MCMC result, Uniform prior')
lines(grid,Unif_post(grid))
plot(seq(1,100001,by=1),mcmcu$chain, type="l", xlab = "iterations", ylab = "chain positions", main = "MCMC chain")
plot(acf(mcmcu$chain, lag.max = 500, plot = FALSE)$acf, ylab = "ACF", xlab = "Lags", main="ACF function")

bsum <- c( mean_btot, var_btot, median(Bpost_tot,space), conf(Bpost_tot,space,0.95)[1], conf(Bpost_tot,space,0.95)[2])
mcmcsum <- c( mean(mcmcu$samples), sd(mcmcu$samples)^2, cumlative_hist(h,0)[1], cumlative_hist(h,0.95)[1], cumlative_hist(h,0.95)[2])
summa <- rbind(bsum,mcmcsum)

rownames(summa) <- c('By integration','MCMC procedure')
colnames(summa) <- c('Mean', 'Variance','Median','Lower bound 95% credibility','Upper bound 95% credibility')

summa <- as.data.frame(round(summa,4))
print(summa)

```

```{r}

h <- hist(mcmcj$samples,breaks=200,plot = FALSE)
h$counts <- h$counts/length(h$counts)
plot(h, ylim= c(0,13), main = 'Histogram of the MCMC result, Uniform prior')
lines(grid,Jeffrey_post(grid))
plot(seq(1,100001,by=1),mcmcj$chain, type="l", xlab = "iterations", ylab = "chain positions", main='MCMC chain')
plot(acf(mcmcj$chain, lag.max = 500, plot = FALSE)$acf, ylab = "ACF", xlab = "Lags", main= 'ACF function')

jsum <- c( mean_btot, var_btot, median(Bpost_tot,space), conf(Bpost_tot,space,0.95)[1], conf(Bpost_tot,space,0.95)[2])
mcmcsum <- c( mean(mcmcu$samples), sd(mcmcu$samples)^2, cumlative_hist(h,0)[1], cumlative_hist(h,0.95)[1], cumlative_hist(h,0.95)[2])
summa <- rbind(jsum,mcmcsum)

rownames(summa) <- c('By integration','MCMC procedure')
colnames(summa) <- c('Mean', 'Variance','Median','Lower bound 95% credibility','Upper bound 95% credibility')

summa <- as.data.frame(round(summa,4))
print(summa)

```

EX 2

```{r}
n <- 116
r <- 11
N <- 1000

prob <- seq(from =0.01, to =N, by=1)/N
pe <- r/n
cat("For the frequentist approach p is:", round(pe,3))

bprior <- dbeta(prob, shape1 = 1, shape2 = 10)
like <- dbinom(x=r, size=n, prob)
Z <- PartFunc(like*bprior,1/N)
Bpost <- like*bprior/Z

cat("\nThe bayesian estimator for p is:",which.max(Bpost)*1/N, "\nThe mean and variance are:",round(sum(prob*Bpost*1/N),3),round(sum(prob*prob*Bpost*1/N)-sum(prob*Bpost*1/N)*sum(prob*Bpost*1/N),3), "\nThe 95% credibility interval is:", conf(Bpost,1/N,0.95)[1],"-", conf(Bpost,1/N,0.95)[2])

plot(prob,Bpost, type = "l", xlim= c(0,0.3), col="blue")
abline(v=c(which.max(Bpost)*1/N,sum(prob*Bpost*1/N),conf(Bpost,1/N,0.95)), col= c("black","red","darkgreen","darkgreen"))

legend(x="topright",legend=c("Posterior","Max","Mean", "95% credibility interval"), col=c("blue","black","red","darkgreen"),lty=c(1,1,1,1), cex=0.8)

```

```{r}
real_freq <- rbinom(n=1000000, size=n, 0.1)

h <- hist(real_freq, breaks = max(real_freq) ,plot=FALSE)
h$counts <- cumsum(h$counts)
h$counts <- h$counts/h$counts[length(h$counts)]

plot(h, col = "lightblue", xaxt="n" ,xlim=c(-1,max(real_freq)), main = "Cumulative Function of Binomial (size=116,0.1)")

axis(side=1,at=h$mids,labels=seq(min(real_freq),max(real_freq)-1))
axis(side=2,at=seq(-1,1,0.1),labels=seq(-1,1,0.1))
abline(h=0.05, col="black", lty=2, lwd= 2)

cat("The null hypothsis of p= 0.1 is accepted, because we can see that 11 extractions over 116 trial is inside the 95% confidence level, because it is above the vertical line drawn at 0.05")
```

```{r}
cat("The upper 95% confidence limit for a Uniform prior posterior is",conf_tails(Bpost, 1/N, 0.95 ,"higher" ))
cat("\nThe 95% confidence interval for a Uniform prior posterior",conf(Bpost, 1/N, 0.95))

cat("\nBayesian analysis on the Posterior \n")

cat("\nThe hypothesis test is accepted if we consider a double tail confidence interval, giving lower and upper values 0.05 - 0.151, which coincides with the hypothesis of p=0.1. On the other hand, if we take the upper tail interval, so we integrate till the 95%, we can conclude that the hypothesis test is rejected, due to the upper limit value of 0.14")
```

```{r}
n <- 165
r <- 9
pe <- r/n

cat("For the frequentist approach p is:", round(pe,3))
bprior <- dbeta(prob, shape1 = 1, shape2 = 10)
prevprior <- Bpost

like <- dbinom(x=r, size=n, prob)
Zb <- PartFunc(like*bprior,1/N)
Zp <- PartFunc(like*prevprior,1/N)
Bpost <- like*bprior/Z
Ppost <- like*prevprior/Zp

cat("\nWith a Beta(1,10) prior")
cat("\nThe bayesian estimator for p is:",which.max(Bpost)*1/N, "\nThe mean and variance are:",sum(prob*Bpost*1/N),sum(prob*prob*Bpost*1/N)-sum(prob*Bpost*1/N)*sum(prob*Bpost*1/N), "\nThe 95% credibility interval is:", conf(Bpost,1/N,0.95),"\n" )
cat("\nWith the prior as the last posterior")
cat("\nthe bayesian estimator for p is:",which.max(Ppost)*1/N, "\nthe mean and variance are:",sum(prob*Ppost*1/N),sum(prob*prob*Ppost*1/N)-sum(prob*Ppost*1/N)*sum(prob*Ppost*1/N), "\nthe 95% credibility interval is:", conf(Ppost,1/N,0.95) )

plot(prob,Bpost, type = "l", xlim= c(0,0.2), col="blue", lwd=2, main= "Post With beta prior" )
abline(v=c(which.max(Bpost)*1/N,sum(prob*Bpost*1/N),conf(Bpost,1/N,0.95)), col= c("black","red","darkgreen","darkgreen"),lwd=c(2,2,2,2))

plot(prob,Ppost, type = "l", xlim= c(0,0.2), col="blue", lwd=2, main = "Post With prior = last posterior" )
abline(v=c(which.max(Ppost)*1/N,sum(prob*Ppost*1/N),conf(Ppost,1/N,0.95)), col= c("black","red","darkgreen","darkgreen"), lwd=c(2,2,2,2))

legend(x="topright",legend=c("Posterior","Max","Mean", "95% credibility interval"), col=c("blue","black","red","darkgreen"),lty=c(1,1,1,1), cex=0.8)
```

```{r}
real_freq <- rbinom(n=1000000, size=n, 0.1)

h <- hist(real_freq, breaks = max(real_freq) ,plot=FALSE)
h$counts <- cumsum(h$counts)
h$counts <- h$counts/h$counts[length(h$counts)]

plot(h, col = "lightblue", xaxt="n" ,xlim=c(-1,max(real_freq)), main = "Cumulative Function of Binomial (size=165,p=0.1)")

axis(side=1,at=h$mids,labels=seq(min(real_freq),max(real_freq)-1))
axis(side=2,at=seq(-1,1,0.1),labels=seq(-1,1,0.1))
abline(h=0.05, col="black", lty=2, lwd= 2)

cat("The null hypothsis of p= 0.1 can be accepted but it is around the thresold value, because we can see that 9 extractions over 116 trial is a bit inside the 95% confidence level, because it is above the vertical line drawn at 0.05. The actual value of the bin of 9 extractions depend on the number of sampled points, so there is an uncertainty around that value.")
```

```{r}
cat("The upper 95% confidence limit for a Beta(1,10)-prior posterior is",conf_tails(Bpost, 1/N, 0.95 ,"higher" ))
cat("\nThe upper 95% confidence limit for the last-posterrior prior posterior is",conf_tails(Ppost, 1/N, 0.95 ,"higher" )) 
cat("\nThe 95% confidence interval for a Beta(1,10)-prior posterior",conf(Bpost, 1/N, 0.95))
cat("\nThe 95% confidence interval for a last-posterior prior posterior",conf(Ppost, 1/N, 0.95),"\n")

cat("\nBayesian analysis on Beta(1,10)-prior Posterior \n")

cat("\nThe hypothesis test is rejected if we consider a double tail confidence interval, giving lower and upper values 0.028 - 0.095, which coincides with the hypothesis of p=0.1. On the other hand, if we take the upper tail interval, so we integrate till the 95%, we can conclude that the hypothesis test is rejected, due to the upper limit value of 0.88\n")

cat("\nBayesian analysis on last-Posterior-Prior Posterior \n")

cat("\nThe hypothesis test is accepted if we consider a double tail confidence interval, giving lower and upper values 0.045 - 0.104, which coincides with the hypothesis of p=0.1. On the other hand, if we take the upper tail interval, so we integrate till the 95%, we can conclude that the hypothesis test is rejected, due to the upper limit value of 0.98")
```

```{r}

library(coda)
library(rjags)

model <- "model{

  # Likelihood
  y ~ dbinom(theta, n)

  # Prior
  theta ~ dbeta(1, 1)

}"

datalist <- list(y= 9, n= 165)

jm <- jags.model(file= textConnection(model), data= datalist, n.chains = 5)

update(jm, n.iter = 1000)

Nrep = 1000000 

posterior_sample <- coda.samples(jm,
                       variable.names = c("theta"),
                       n.iter = Nrep)

p
qnor
```

```{r}
summary(posterior_sample)
plot(posterior_sample)

```
